[package]
name = "typst-lsp"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
tower-lsp = "0.19.0"
tokio = { version = "1.26.0", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
] }
